services:
    paybas.recenttopics.admin.controller:
        class: paybas\recenttopics\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@request'
            - '@dbal.conn'
            - '@ext.manager'

    paybas.recenttopics.functions:
        class: paybas\recenttopics\core\recenttopics
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@language'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@?part3.topicprefixes.functions'
            - '@?prefixed.manager'
            - '@?phpbb.collapsiblecategories.operator'

    paybas.recenttopics.listener:
        class: paybas\recenttopics\event\listener
        arguments:
            - '@paybas.recenttopics.functions'
            - '@config'
            - '@request'
        tags:
            - { name: event.listener }

    paybas.recenttopics.ucp_listener:
        class: paybas\recenttopics\event\ucp_listener
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
